server:
  enable_rest: true
  rest_port: ":8080"
  enable_grpc: true
  grpc_port: ":50051"
logger:
  is_dev: true
simulation:
  deterministic: false
  seed: 42
  use_mock_topology: false
  enable_metrics: true
  load_from_save: false
  db_type: "json" # "json" или "postgres"
database:
  host: "localhost"
  port: 5432
  user: "hellgame_user"
  password: "--secret--"
  dbname: "hellgame_project"
  sslmode: "disable"