package main

// createInitialFactions создаёт начальные фракции мира
func createInitialFactions() map[string]*FactionState {
	return map[string]*FactionState{
		FactionCorporateConsortium: {
			ID:             FactionCorporateConsortium,
			Name:           "Corporate Consortium",
			Power:          70,
			Territory:      3.5,
			DomainsHeld:    []string{DomainLust, DomainGreed},
			Attitude:       make(map[string]float64),
			Resources:      80,
			MilitaryForce:  75,
			LastActionTime: 0,
		},
		FactionRepentantCommunes: {
			ID:             FactionRepentantCommunes,
			Name:           "Repentant Communes",
			Power:          50,
			Territory:      1.8,
			DomainsHeld:    []string{DomainGluttony},
			Attitude:       make(map[string]float64),
			Resources:      40,
			MilitaryForce:  35,
			LastActionTime: 0,
		},
		FactionNeoTormentors: {
			ID:             FactionNeoTormentors,
			Name:           "Neo-Tormentors",
			Power:          65,
			Territory:      2.5,
			DomainsHeld:    []string{DomainWrath, DomainViolence},
			Attitude:       make(map[string]float64),
			Resources:      70,
			MilitaryForce:  85,
			LastActionTime: 0,
		},
		FactionCaravanGuilds: {
			ID:             FactionCaravanGuilds,
			Name:           "Caravan Guilds",
			Power:          45,
			Territory:      0.9,
			DomainsHeld:    []string{DomainLimbo},
			Attitude:       make(map[string]float64),
			Resources:      60,
			MilitaryForce:  40,
			LastActionTime: 0,
		},
		FactionAncientRemnants: {
			ID:             FactionAncientRemnants,
			Name:           "Ancient Remnants",
			Power:          30,
			Territory:      0.3,
			DomainsHeld:    []string{DomainHeresy},
			Attitude:       make(map[string]float64),
			Resources:      50,
			MilitaryForce:  60,
			LastActionTime: 0,
		},
	}
}

// createInitialDomains создаёт начальные домены (9 кругов ада)
func createInitialDomains() map[string]*DomainState {
	return map[string]*DomainState{
		DomainLimbo: {
			ID:           DomainLimbo,
			Name:         "Limbo",
			Stability:    60,
			ControlledBy: FactionCaravanGuilds,
			DangerLevel:  3,
			Population:   5000,
			Mood:         "stable",
			Influence:    make(map[string]float64),
		},
		DomainLust: {
			ID:           DomainLust,
			Name:         "Circle of Lust",
			Stability:    40,
			ControlledBy: FactionCorporateConsortium,
			DangerLevel:  5,
			Population:   3000,
			Mood:         "exploited",
			Influence:    make(map[string]float64),
		},
		DomainGluttony: {
			ID:           DomainGluttony,
			Name:         "Circle of Gluttony",
			Stability:    50,
			ControlledBy: FactionRepentantCommunes,
			DangerLevel:  4,
			Population:   2500,
			Mood:         "hopeful",
			Influence:    make(map[string]float64),
		},
		DomainGreed: {
			ID:           DomainGreed,
			Name:         "Circle of Greed",
			Stability:    35,
			ControlledBy: FactionCorporateConsortium,
			DangerLevel:  6,
			Population:   4000,
			Mood:         "unrest",
			Influence:    make(map[string]float64),
		},
		DomainWrath: {
			ID:           DomainWrath,
			Name:         "Circle of Wrath",
			Stability:    20,
			ControlledBy: FactionNeoTormentors,
			DangerLevel:  9,
			Population:   6000,
			Mood:         "terrified",
			Influence:    make(map[string]float64),
		},
		DomainHeresy: {
			ID:           DomainHeresy,
			Name:         "Circle of Heresy",
			Stability:    45,
			ControlledBy: FactionAncientRemnants,
			DangerLevel:  7,
			Population:   1000,
			Mood:         "mysterious",
			Influence:    make(map[string]float64),
		},
		DomainViolence: {
			ID:           DomainViolence,
			Name:         "Circle of Violence",
			Stability:    15,
			ControlledBy: FactionNeoTormentors,
			DangerLevel:  10,
			Population:   8000,
			Mood:         "chaotic",
			Influence:    make(map[string]float64),
		},
		DomainFraud: {
			ID:           DomainFraud,
			Name:         "Circle of Fraud",
			Stability:    30,
			ControlledBy: "none",
			DangerLevel:  8,
			Population:   2000,
			Mood:         "deceptive",
			Influence:    make(map[string]float64),
		},
		DomainBetrayance: {
			ID:           DomainBetrayance,
			Name:         "Ninth Circle",
			Stability:    10,
			ControlledBy: "none",
			DangerLevel:  10,
			Population:   500,
			Mood:         "despairing",
			Influence:    make(map[string]float64),
		},
	}
}
